// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssucboxhsiejdomhqqds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzdWNib3hoc2llamRvbWhxcWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODM0MjMsImV4cCI6MjA3NDA1OTQyM30.G7tkd_rfF081wTjEU-UY1d6YpNkBU1yvlTzdyhed9Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});